cmake_minimum_required(VERSION 4.3)
project(Data_Structers)

set(CMAKE_CXX_STANDARD 20)

add_executable(Data_Structers main.cpp)
add_executable(1.2.1_exec c++回顾/传值参数.cpp)
add_executable(1.2.2_exec c++回顾/函数模版.cpp)
add_executable(1.2.3_exec c++回顾/引用参数.cpp)
add_executable(1.2.4_exec c++回顾/常量引用参数.cpp)
add_executable(1.2.6.1_exec c++回顾/c++回顾练习/练习1.cpp)
add_executable(1.2.6.2_exec c++回顾/c++回顾练习/练习2.cpp)
add_executable(1.2.6.3_exec c++回顾/c++回顾练习/练习3.cpp)
